import { Metadata, NextPage } from 'next';

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
  };

const SignInPage: NextPage = () => {
    return (
        <div>
            <h1>Sign In</h1>
            {/* Your sign in form goes here */}
        </div>
    );
};

export default SignInPage;